apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sb-kube
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: sb-kube-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10