apiVersion: v1
items:
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2018-04-05T20:34:19Z
    name: sb-kube-deployment
    namespace: default
    resourceVersion: "99517"
    selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/sb-kube-deployment
    uid: b782fd5f-3910-11e8-bb4e-0a58ac1f010a
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 10
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: sb-kube-deployment
  status:
    conditions:
    - lastTransitionTime: 2018-04-05T20:34:49Z
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: 2018-04-05T20:34:49Z
      message: 'the HPA was unable to compute the replica count: missing request for
        cpu on container sb-kube in pod default/sb-kube-deployment-6dd6ccf559-99v6q'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics: null
    currentReplicas: 3
    desiredReplicas: 0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
